name: Fetch Hotstar Events

on:
  schedule:
    - cron: "*/10 * * * *" # runs every 10 minutes
  workflow_dispatch: # allow manual trigger

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch API data
        run: |
          curl -s "${{ secrets.API_URL }}" -o jiohotstar-events.json

      - name: Update Gist
        uses: andymckay/gist-action@v1
        with:
          gist_id: "${{ secrets.GIST_ID }}"
          file_path: jiohotstar-events.json
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
